# Generated by Django 3.2.4 on 2021-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210610_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'new'), ('A', 'accepted'), ('F', 'failed')], default='N', max_length=12),
        ),
    ]
